### PR TITLE
finalize module + flake apps

### PR DESCRIPTION
**Pull request by DavHau**
based on https://github.com/ngi-nix/IRMAseal/pull/1

This is the result of our Team 7 group peer coding session from 2021-09-07 with @NerdyPepper @humancalico @happysalada @raghuramlavan @DavHau @cdepillabout 

Things done:
- finalize nixos module (systemd service)
- add flake check to test the module in a VM
- add a flake app to debug the module in nixos-shell
- add flake app for generating keys

### CODE REVIEW

**Comment by oppiliappan** [comment]
This looks solid to me, @happysalada, @humancalico would you like to take a look?

**Comment by happysalada** [comment]
I'm happy with this at the moment.
I need a bit more time to meditate on what we did and if we did the right thing. Right now I don't have an answer, so what we have is good enough. I do have some feeling though that later on, we will be like "duh, why didn't we do X". For now though, as far as I'm concerned, feel free to merge this.

**Comment by oppiliappan** [comment]
>I do have some feeling though that later on, we will be like "duh, why didn't we do X"

We can definitely come back to this later. I'll wait for @humancalico to weigh in and merge this.

**Comment by akshatagarwl** [comment]
Looks great!

**Pull request merged**
